<div id="fb-root"></div>

<?php
$title = 'Post an Internship';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('%s'.$title.'%s'), '<span class="zf-green">', '</span>') ?></h1>
    <?php
    $form = $this->form;
	$form->setAttribute('action', $this->url('interns', array('action' => 'add')));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo $this->formHidden($form->get('employer_id'));
	?>
	<table>
		<tr>
			<td valign="top">
		<label>Fill in the form below</label>
		<table id='simpleForm'>
		<tr>
			<td><?php echo $this->formLabel($form->get('title')); ?></td>
			<td><?php echo $this->formInput($form->get('title')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("title"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
		<tr>
			<td><?php echo $this->formLabel($form->get('description')); ?></td>
			<td><?php echo $this->formTextarea ($form->get('description')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("description"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
                <tr>
			<td><?php echo $this->formLabel($form->get('field_category_id')); ?></td>
			<td><?php echo $this->formMultiCheckbox($form->get('field_category_id')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("field_category_id"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
		<tr>
			<td><?php echo $this->formLabel($form->get('reuirements')); ?></td>
			<td><?php echo $this->formTextarea ($form->get('reuirements')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("reuirements"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
		<tr>
			<td><?php echo $this->formLabel($form->get('responsbilities')); ?></td>
			<td><?php echo $this->formTextarea ($form->get('responsbilities')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("responsbilities"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
		<tr>
			<td><?php echo $this->formLabel($form->get('address')); ?></td>
			<td><?php echo $this->formTextarea ($form->get('address')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("address"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
		<tr>
			<td><?php echo $this->formLabel($form->get('location_id')); ?></td>
			<td><?php echo $this->formSelect($form->get('location_id')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("location_id"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
		<tr>
			<td><?php echo $this->formLabel($form->get('is_fulltime')); ?></td>
			<td><?php echo $this->formRadio($form->get('is_fulltime')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("is_fulltime"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
                
                <tr>
			<td><?php echo $this->formLabel($form->get('is_paid')); ?></td>
			<td><?php echo $this->formRadio($form->get('is_paid')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("is_paid"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
                <tr>
			<td><?php echo $this->formLabel($form->get('is_available_anytime')); ?></td>
			<td><?php echo $this->formRadio($form->get('is_available_anytime')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("is_available_anytime"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
		<tr>
                <tr>
			<td><?php echo $this->formLabel($form->get('duration')); ?></td>
			<td><?php echo $this->formInput($form->get('duration')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("duration"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
		<tr>
                <tr>
			<td><?php echo $this->formLabel($form->get('is_duration_flexible')); ?></td>
			<td><?php echo $this->formRadio($form->get('is_duration_flexible')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("is_duration_flexible"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
		<tr>
                <tr>
			<td><?php echo $this->formLabel($form->get('minimum_duration')); ?></td>
			<td><?php echo $this->formInput($form->get('minimum_duration')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("minimum_duration"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
                <tr>
			<td><?php echo $this->formLabel($form->get('is_virtual')); ?></td>
			<td><?php echo $this->formCheckbox($form->get('is_virtual')); ?></td>
		</tr>
		<tr>
			<td colspan='2' ><?php echo $this->formElementErrors($form->get("is_virtual"), array('class' => "formError", 'message' => "errormessage")); ?> </td>
		</tr>
		<tr>
			<td colspan='2'><div class="btn btn-success btn-lg" ><?php echo $this->formSubmit($form->get('submit')); ?></div></td>
		</tr>
	</table></td>
	</tr>
	</table>
	<?php
	
	echo "<br/>";
	echo $this->form()->closeTag();
    
    ?>
</div>